### ISSUE TITLE
Windows System

### ISSUE THREAD

**Issue by MfaXyz** [bepass-org/oblivion#12]
Hello, Please add windows version.

**Comment by comm4nd3rx** [comment]
you can use core version for windows/mac/linux

https://github.com/bepass-org/wireguard-go

**Comment by MfaXyz** [comment]
> you can use core version for windows/mac/linux
> 
> https://github.com/bepass-org/wireguard-go

Will it perform similarly to Oblivion on Android?

**Comment by comm4nd3rx** [comment]
yeah, its the same exact core that is being used in Oblivion ( its even better since some of its features havent been implemented in Oblivion "for now")

**Comment by sallyoneee** [comment]
> yeah, its the same exact core that is being used in Oblivion ( its even better since some of its features havent been implemented in Oblivion "for now")

![nss](https://github.com/bepass-org/oblivion/assets/33378971/3f399ff1-2466-42d4-a6ef-1994fc93c86d)
I get this error, do you know how to fix it?

**Comment by MfaXyz** [comment]
> yeah, its the same exact core that is being used in Oblivion ( its even better since some of its features havent been implemented in Oblivion "for now")

I tried this [README.md](https://github.com/bepass-org/wireguard-go/blob/master/README.md) is deprecated and none of the instructions work.

**Comment by comm4nd3rx** [comment]
@MfaXyz @sallyoneee 

first of all, download the binary from [release section](https://github.com/bepass-org/wireguard-go/releases/tag/v1.0.2-rc1)

after that, if you are using Windows, just exact the .exe file and run it using cmd
if you are using Linux, you should give it permission to run as an executable (using chmod +x)

also, I'd appreciate it if you could create an issue regarding Windows in the core repo, since its irrelevant here

**Comment by markpash** [comment]
Windows version is now available here: https://github.com/bepass-org/oblivion-desktop/releases
