### ISSUE TITLE
Connecting

### ISSUE THREAD

**Issue by DARKERthanDA** [bepass-org/oblivion#13]
In app even though when you check log and it say it's connected, the UI is stock at connecting but everything is working just fine so it's a UI bug. (When warp in warp is on)

**Comment by ameerhossein** [comment]
I can't reproduce the issue. I've rewritten the connection state handling in 0.0.8-test release and some minor patches in 0.0.10 which is not released yet. Please wait for 0.0.10-test release and see if the problem is still there. If it was not fixed, please provide the steps to reproduce the issue.
